import axios from 'axios'

const REGISTERING = "REGISTERING"
const REGISTER_SUCCESS = "REGISTER_SUCCESS"
const REGISTER_FAILURE = "REGISTER FAILURE"

const LOGGING_IN = "LOGGING_IN"
const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
const LOG_IN_FAILURE = "LOG_IN_FAILURE"